name: Remove old artifacts

on:
  schedule:
    # 1st of every month at 1am
    - cron: '0 19 1 * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 month'
        skip-tags: true
